version: "3.3"
volumes:
  db:
    driver:
      local
services:
  #PHP Service
  ad:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: ad
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ad-group

  #MySQL Service
  addb:
    image: mysql:8.0.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ad_task
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3399:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - ad-group

  redis:
    image: redis:latest
    container_name: ad_redis
    ports:
      - "6683:6379"
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
    networks:
      - ad-group

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginxad
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./touch.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ad-group

#Docker Networks
networks:
  ad-group:
    driver: bridge
